substitutions:
  project: Cistern
  id: cistern
  hostname: cistern
  log_level: INFO

esphome:
  name: $hostname

esp8266:
  board: thing

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

i2c:
  sda: 2
  scl: 14
  scan: True

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

captive_portal:
    
sensor:
  - platform: vl53l0x
    name: "Distance"
    address: 0x29
    update_interval: 60s
    long_range: true
