substitutions:
  project: Soil Moisture
  id: soilmoisture1
  hostname: soilmoisture1
  log_level: INFO

esphome:
  name: $hostname

esp8266:
  board: esp12f

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

status_led:
  pin:
    number: D7
    inverted: True

i2c:
  sda: D4
  scl: D5
  scan: True

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

captive_portal:

# Clock Output for soil moisture sensor
output:
  - platform: esp8266_pwm
    pin: D5
    frequency: 60000 Hz
    id: pwm_output

# Soil moisture sensor
sensor:
  - platform: adc
    unit_of_measurement: "%"
    icon: "mdi:flower-outline"
    accuracy_decimals: 0
    pin: A0
    filters:
    - calibrate_linear:
        - 0.38 -> 100
        - 0.7 -> 0
    name: "Soil Moisture Level"
    update_interval: 300s

on_boot:
  then:
    - output.set_level:
        id: pwm_output
        level: 8%  