substitutions:
  project: Soil Moisture
  id: soilmoisture1
  hostname: soilmoisture1
  log_level: DEBUG

esphome:
  # libraries:
  #   - Wire
  name: $hostname

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

status_led:
  pin:
    number: GPIO13
    inverted: True

i2c:
  sda: 4
  scl: 5

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

captive_portal:

external_components:
  - source:
      type: local
      path: custom_components

number:
  - platform: template
    id: sensor_dry_adc
    min_value: 0
    max_value: 1024
    initial_value: 248
    step: 1
    name: ADC Dry
    entity_category: config
    optimistic: true
    on_value: 
      then:
        - lambda: 'id(soilsensor).set_adc_dry_at_3v(x);'
  - platform: template
    id: sensor_wet_adc
    min_value: 0
    max_value: 1024
    initial_value: 123
    step: 1
    name: ADC Wet
    entity_category: config
    optimistic: true
    on_value: 
      then:
        - lambda: 'id(soilsensor).set_adc_wet_at_3v(x);'

sensor:
  - platform: tmp112
    id: temperature
    name: Temperature
    update_interval: 5min
  - platform: ap_soil_moisture_sensor
    id: soilsensor
    battery_level:
      name: "Battery"
    battery_level_raw:
      name: "Battery RAW"
    moisture:
      name: "Moisture"
    moisture_raw:
      name: "Moisture RAW"
    update_interval: 60min

binary_sensor:
  - platform: gpio
    pin: 
      number: 12
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Send Reading"
    entity_category: config
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - lambda: 'id(soilsensor).update();'
